### ISSUE TITLE
Possible Prototype Adapter Error? 

### ISSUE THREAD

**Issue by donlee8** [enyo/opentip#12]
I'm using the prototype adapter and am getting this JS error at line 129 or opentip.js:

Uncaught TypeError: Cannot read property 'length' of undefined

options.hideTriggers is null instead of the default empty array. I tried setting it explicitly in my options but I still get the error. It looks like the culprit may be the previous call to the extend method in the prototype adapter:

options = (_ref = this.adapter).extend.apply(_ref, [{}].concat(__slice.call(optionSources)));

Let me know if you need more info. Thanks!

**Comment by enyo** [comment]
Thanks for your feedback. I really should have tested the prototype adapter a bit more... I'll look into it.

**Comment by enyo** [comment]
I'm really sorry for this, I thought that it was enough that all tests passed, and didn't test it in the browser.
I added tests so that the stuff that got through wouldn't again.

I really shouldn't have released it without actually testing the prototype version at least _once_.

Thanks for pointing it out.

**Comment by donlee8** [comment]
That was quick, thanks for the prompt fix!
